# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 02182840401bb0e1798ad7b7ac3bedc147b51016f6ea37f0f8c160fd1691c7e1abb7200b9dfc9e2674c8b0a826103cb4602cb1b792fe7504aa35aa9863a84ac1

test:
  secret_key_base: dfab37dad2c6fad02c1a7d9eaff464a2da123f31b0197433c1b9e5628d51e87fc34ee03b0656f9f5529aef5b66b4da054e7fadb4a0de42335c140f27b4702c36

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
